service: gdg2024lab

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-2'}
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  profile: default
  environment:
    STAGE: ${self:provider.stage}
    BUCKET_NAME: ${self:custom.bucketName}
    STUDENTS_TABLE: ${self:custom.student}

custom:
  bucketName: students-bucket-${self:provider.stage}
  apiVersion: v1
  student: students-table-${self:provider.stage}

  commonIamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"

    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::${self:custom.bucketName}/*
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.student}

functions:
  createStudents:
    handler: ./src/functions/student/create.handler
    description: Creates a new student
    events:
      - http:
          path: /api/${self:custom.apiVersion}/students
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.student}

  listStudents:
    handler: ./src/functions/student/list.handler
    description: Get list of students
    events:
      - http:
          path: /api/${self:custom.apiVersion}/students
          method: GET
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.student}


resources:
  Resources:
    DonkounBucket: ${file(resources/create-s3-bucket.yml):StudentS3Bucket}
    DonkounTripsDynamoDBTable: ${file(resources/create-dynamodb-tables.yml):StudentDynamoDBTable}
